### PR TITLE
Fix the warnings I can see.

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Might address #9, not sure @cooljeanius?

I'm not 100% confident that all these changes are correct.

There's also a bajillion "might be nil" warnings in wml-tags.lua, but I'm pretty sure all of them are because the linter doesn't understand that wml.error will never return.

### CODE REVIEW

**Comment by cooljeanius** [comment]
> Might address #9, not sure @cooljeanius?

Actually it increases the number of warnings there from 13 to 16:
```
$ luacheck-5.3 .
Checking animation.lua                            2 warnings

    animation.lua:516:38: (W421) shadowing definition of variable x on line 495
    animation.lua:516:41: (W421) shadowing definition of variable y on line 495

Checking debug_utils.lua                          2 warnings

    debug_utils.lua:65:42: (W431) shadowing upvalue index on line 58
    debug_utils.lua:172:10: (W421) shadowing definition of variable result on line 35

Checking gui-tags.lua                             5 warnings

    gui-tags.lua:130:10: (W431) shadowing upvalue temp_table on line 35
    gui-tags.lua:204:9: (W411) variable temp_table was previously defined on line 35
    gui-tags.lua:269:50: (W542) empty if branch
    gui-tags.lua:295:1: (W611) line contains only whitespace
    gui-tags.lua:454:50: (W542) empty if branch

Checking wlp_utils.lua                            4 warnings

    wlp_utils.lua:11:29: (W432) shadowing upvalue argument f on line 9
    wlp_utils.lua:11:32: (W432) shadowing upvalue argument t on line 9
    wlp_utils.lua:12:9: (W432) shadowing upvalue argument indent on line 9
    wlp_utils.lua:153:8: (W412) variable char was previously defined as an argument on line 152

Checking wml-tags.lua                             3 warnings

    wml-tags.lua:144:8: (W412) variable cfg was previously defined as an argument on line 143
    wml-tags.lua:388:9: (W421) shadowing definition of variable index on line 370
    wml-tags.lua:641:8: (W423) shadowing definition of loop variable index on line 631

Total: 16 warnings / 0 errors in 5 files
$
```

**Comment by cooljeanius** [comment]
Here's a diff between the old warnings and the new ones: https://gist.github.com/cooljeanius/8c1d0e09dfa40d837bd34eada57f4429

**Comment by CelticMinstrel** [comment]
Nice! It seems my linter isn't warning about shadowing at all… or maybe the nil checks are overwhelming it and some of the other errors are cut off…? Or I don't really know.

For example, I _can_ see a warning on line 204 of gui-tags.cfg if I go to that location. The warning isn't listed in the problems list though…

**Comment by CelticMinstrel** [comment]
I'm not touching the empty if branches or anything related to whitespace, although if someone wants to do whitespace stuff I'm willing to cherry-pick it to my fork.

**Comment by cooljeanius** [comment]
OK so yeah now it's down to 4 luacheck warnings:
```
$ luacheck-5.3 .
Checking gui-tags.lua                             4 warnings

    gui-tags.lua:130:10: (W431) shadowing upvalue temp_table on line 35
    gui-tags.lua:269:50: (W542) empty if branch
    gui-tags.lua:295:1: (W611) line contains only whitespace
    gui-tags.lua:454:50: (W542) empty if branch

Total: 4 warnings / 0 errors in 5 files
$
```

**Comment by cooljeanius** [comment]
> I'm not touching the empty if branches or anything related to whitespace, although if someone wants to do whitespace stuff I'm willing to cherry-pick it to my fork.

I did some whitespace stuff in CelticMinstrel/Wesnoth_Lua_Pack#1

**Comment by CelticMinstrel** [comment]
Obviously it's entirely up to you but personally I would recommend squashing this.

**Review by cooljeanius — APPROVED** [review]

**Pull request merged**
